version: '2.2'

services:
  web:
    build: ./web
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://user:user@postgres
      - LOGGING_LEVEL=DEBUG
      - WEB_SENTRY_DSN
    ports:
      - 0.0.0.0:9000:9000/tcp
    restart: unless-stopped
    #  headlines:
    #    build: ./headlines
    #    depends_on:
    #      - web
    #    environment:
    #      - WEB_URL=http://web:9000/api/articles
    #      - ELASTIC_USER
    #      - ELASTIC_PASS
    #      - HEADLINES_SENTRY_DSN
    #    restart: unless-stopped
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    restart: unless-stopped
